/*
 * This file is generated by jOOQ.
 */
package de.bitcorn.www.pages.database;


import de.bitcorn.www.pages.database.tables.Contact;
import de.bitcorn.www.pages.database.tables.Textures;
import de.bitcorn.www.pages.database.tables.VectorGraphics;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>bitcorn</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONTACT_PRIMARY = Indexes0.CONTACT_PRIMARY;
    public static final Index TEXTURES_PRIMARY = Indexes0.TEXTURES_PRIMARY;
    public static final Index VECTOR_GRAPHICS_PRIMARY = Indexes0.VECTOR_GRAPHICS_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CONTACT_PRIMARY = Internal.createIndex("PRIMARY", Contact.CONTACT, new OrderField[] { Contact.CONTACT.ID }, true);
        public static Index TEXTURES_PRIMARY = Internal.createIndex("PRIMARY", Textures.TEXTURES, new OrderField[] { Textures.TEXTURES.ID }, true);
        public static Index VECTOR_GRAPHICS_PRIMARY = Internal.createIndex("PRIMARY", VectorGraphics.VECTOR_GRAPHICS, new OrderField[] { VectorGraphics.VECTOR_GRAPHICS.ID }, true);
    }
}
