/*
 * This file is generated by jOOQ.
 */
package bitcorn.pages.database;


import bitcorn.pages.database.tables.Contact;
import bitcorn.pages.database.tables.Textures;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bitcorn extends SchemaImpl {

    private static final long serialVersionUID = -1436668230;

    /**
     * The reference instance of <code>bitcorn</code>
     */
    public static final Bitcorn BITCORN = new Bitcorn();

    /**
     * The table <code>bitcorn.contact</code>.
     */
    public final Contact CONTACT = bitcorn.pages.database.tables.Contact.CONTACT;

    /**
     * The table <code>bitcorn.textures</code>.
     */
    public final Textures TEXTURES = bitcorn.pages.database.tables.Textures.TEXTURES;

    /**
     * No further instances allowed
     */
    private Bitcorn() {
        super("bitcorn", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Contact.CONTACT,
            Textures.TEXTURES);
    }
}
